STATUSES = ['PLACED', 'ACCEPTED', 'PREPARING', 'READY', 'COLLECTED', 'CANCELLED']

NEXT_STATUS = {
    'PLACED': 'ACCEPTED',
    'ACCEPTED': 'PREPARING',
    'PREPARING': 'READY',
    'READY': 'COLLECTED'
}
